name: Testing with Pytest

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - 'requirements.txt'
      - '.github/workflows/pytest_action.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pytest
        run: |
          python -m pytest tests/test_shopping_cart_pytest.py --junitxml=pytest-report.xml

      - name: Upload Pytest report
        uses: actions/upload-artifact@v2
        with:
          name: pytest-report
          path: pytest-report.xml
